<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div id="registrationPopup">
    <script type="text/x-magento-init">
        {
            "#registrationPopup": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
</div>
<script>
    window.registrationPopup.formUrl = '<?= $block->getUrl("popup/register/index") ?>';
</script>
